export const books = [
    {
      id: 1,
      title: 'JavaScript and Jquery',
      author: 'Jon Duckett',
      price: '$62',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 2,
      title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
      author: 'Robert C. Martin',
      price: '$45',
      stars: 5,
      thumbnail: '/book.png',
    },
    {
      id: 3,
      title: 'Eloquent JavaScript: A Modern Introduction to Programming',
      author: 'Marijn Haverbeke',
      price: '$30',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 4,
      title: 'The Pragmatic Programmer: Your Journey to Mastery',
      author: 'David Thomas, Andrew Hunt',
      price: '$55',
      stars: 5,
      thumbnail: '/book.png',
    },
    {
      id: 5,
      title: 'Python Crash Course',
      author: 'Eric Matthes',
      price: '$40',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 6,
      title: 'Design Patterns: Elements of Reusable Object-Oriented Software',
      author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
      price: '$60',
      stars: 5,
      thumbnail: '/book.png',
    },
    {
      id: 7,
      title: 'The Web Developer Bootcamp 2022',
      author: 'Colt Steele',
      price: '$49',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 8,
      title: 'Node.js Design Patterns',
      author: 'Mario Casciaro',
      price: '$48',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 9,
      title: 'Learning React: Modern Patterns for Developing React Apps',
      author: 'Alex Banks, Eve Porcello',
      price: '$35',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 10,
      title: 'Java: The Complete Reference',
      author: 'Herbert Schildt',
      price: '$58',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 11,
      title: 'Full Stack Development with Spring Boot and React',
      author: 'Juha Hinkula',
      price: '$52',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 12,
      title: 'Learning Python',
      author: 'Mark Lutz',
      price: '$45',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 13,
      title: 'C# 9.0 in a Nutshell: The Definitive Reference',
      author: 'Joseph Albahari, Ben Albahari',
      price: '$55',
      stars: 5,
      thumbnail: '/book.png',
    },
    {
      id: 14,
      title: 'Effective Java',
      author: 'Joshua Bloch',
      price: '$50',
      stars: 5,
      thumbnail: '/book.png',
    },
    {
      id: 15,
      title: 'Docker Deep Dive',
      author: 'Nigel Poulton',
      price: '$38',
      stars: 4,
      thumbnail: '/book.png',
    },
    {
      id: 16,
      title: 'Machine Learning Yearning',
      author: 'Andrew Ng',
      price: '$42',
      stars: 5,
      thumbnail: '/book.png',
    },
  ];
  